name: ci

on:
  push:
    branches:
      - main
      - 4-add-unit-test-to-sample-app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use NodeJS version ${{ matrix.node-version}}
          uses: actions/checkout@v3
          with:
            node-version: ${{ matrix.node-version}}
        - run: npm ci
        - run: npm test